"""initial migration

Revision ID: 303987ea498b
Revises: None
Create Date: 2025-06-12 23:36:02.080847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '303987ea498b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('users', sa.Column('password_set_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_set_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_set_token_expires')
    op.drop_column('users', 'password_set_token')
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###